"""
Write tools for the NL → dbt agent.

create_dbt_model — write SQL to models/marts/, run dbt compile, return errors.
                   The agent retries with fixed SQL if compile fails (max 2 attempts
                   enforced in the agent system prompt, not here).

Safety rules:
  - Only writes to models/marts/ — never touches silver, gold, staging folders.
  - Model name is sanitised (alphanumeric + underscore only).
  - dbt compile runs with --no-version-check to avoid env mismatch errors.
  - Writes are logged to audit_store so there's a record of every model created.
"""

import os
import re
import subprocess
from pathlib import Path
from langchain_core.tools import tool

from memory.audit_store import log_action

_DBT_PROJECT_DIR = os.getenv(
    "DBT_PROJECT_DIR",
    "/home/kishore/enterprise-datalake/transformation/dbt/datalake_transforms",
)
_MARTS_DIR = Path(_DBT_PROJECT_DIR) / "models" / "marts"


def _safe_name(name: str) -> str:
    """Sanitise model name: lowercase, alphanumeric + underscore only."""
    return re.sub(r"[^a-z0-9_]", "_", name.lower().strip())


def _normalise_sql(sql: str) -> str:
    """Strip any LLM-written config blocks and convert direct table refs to {{ ref() }}.
    Allows the LLM to write plain SQL (gold.fct_orders) instead of Jinja to avoid
    curly-brace issues in JSON tool call parameters."""
    import re as _re
    # Remove any {{ config(...) }} block the LLM may have included
    sql = _re.sub(r'\{\{-?\s*config\s*\(.*?\)\s*-?\}\}\s*', '', sql, flags=_re.DOTALL)
    # gold.fct_orders  →  {{ ref('fct_orders') }}
    sql = _re.sub(
        r'\b(?:gold|staging)\.((?:fct_|dim_|stg_|mart_)\w+)\b',
        lambda m: "{{ ref('" + m.group(1) + "') }}",
        sql,
    )
    return sql.strip()


_CONFIG_BLOCK = (
    "{{ config(schema='gold', materialized='table', "
    "engine='MergeTree()', order_by='tuple()') }}\n\n"
)


@tool
def create_dbt_model(model_name: str, sql: str) -> str:
    """Write a new dbt SQL model to models/marts/ and validate it with dbt compile.
    Returns 'SUCCESS' with the model path, or the compile error for the agent to fix.
    model_name: snake_case name (e.g. 'fct_reactivated_users')
    sql: plain SQL only — no config blocks, no Jinja.
         Write gold.fct_orders instead of ref(). The tool adds config and ref() automatically."""
    safe = _safe_name(model_name)
    if not safe:
        return "Error: model_name is invalid after sanitisation."

    model_path = _MARTS_DIR / f"{safe}.sql"
    target     = {"model": safe, "path": str(model_path)}

    # Convert plain SQL references to dbt {{ ref() }} syntax if needed
    sql = _normalise_sql(sql)

    # Prevent overwriting existing production models silently
    if model_path.exists():
        existing = model_path.read_text()
        if "-- generated by nl_dbt_agent" not in existing:
            log_action("create_dbt_model", target, "blocked",
                       reasoning="File exists and was not agent-generated")
            return (
                f"⚠️  `{model_path.name}` already exists and was not created by this agent. "
                "Choose a different model name or confirm overwrite explicitly."
            )

    try:
        # Inject marker + config block; LLM writes plain SQL, tool adds Jinja
        header = f"-- generated by nl_dbt_agent\n-- model: {safe}\n\n"
        model_path.write_text(header + _CONFIG_BLOCK + sql)
    except Exception as e:
        log_action("create_dbt_model", target, "error", error=str(e))
        return f"Error writing model file: {e}"

    # Run dbt compile for this model only (no DB connection needed)
    # Use a writable temp dir — the default target/ may be root-owned in some envs.
    import tempfile as _tmpfile
    dbt_target = os.getenv("DBT_TARGET_PATH", _tmpfile.gettempdir() + "/dbt_target")
    os.makedirs(dbt_target, exist_ok=True)
    try:
        result = subprocess.run(
            ["dbt", "compile", "--select", safe, "--no-version-check",
             "--target-path", dbt_target],
            cwd=_DBT_PROJECT_DIR,
            capture_output=True,
            text=True,
            timeout=60,
        )
        output = result.stdout + result.stderr
        # Filter to just relevant lines
        relevant = [
            line for line in output.splitlines()
            if any(k in line for k in ("ERROR", "error", "Error", "Compiled", "WARN", safe))
        ]
        summary = "\n".join(relevant[:20]) if relevant else output[:500]

        if result.returncode == 0:
            log_action("create_dbt_model", target, "success")
            return (
                f"✅ Model `{safe}` compiled successfully.\n"
                f"Path: `{model_path}`\n\n"
                f"Compile output:\n```\n{summary}\n```\n\n"
                f"Run it with: `dbt run --select {safe}`"
            )
        else:
            # Leave the file on disk so agent can fix it — don't delete
            log_action("create_dbt_model", target, "compile_error", error=summary[:300])
            return (
                f"❌ Compile failed for `{safe}`.\n\n"
                f"Error:\n```\n{summary}\n```\n\n"
                "Fix the SQL and call create_dbt_model again with the corrected version."
            )

    except FileNotFoundError:
        log_action("create_dbt_model", target, "error", error="dbt not found in PATH")
        return (
            "Error: `dbt` not found. "
            "Install dbt-clickhouse: `pip install dbt-clickhouse` "
            "and ensure ~/.dbt/profiles.yml is configured."
        )
    except subprocess.TimeoutExpired:
        log_action("create_dbt_model", target, "error", error="compile timeout 60s")
        return "Error: dbt compile timed out after 60s."
    except Exception as e:
        log_action("create_dbt_model", target, "error", error=str(e))
        return f"Unexpected error during compile: {e}"
