networks:
  frontend-net:
    driver: bridge
    internal: false
  backend-net:
    driver: bridge
    internal: true
  management-net:
    driver: bridge
    internal: true
  keycloak-net:
    driver: bridge
    internal: false

volumes:
  minio-data:
  clickhouse-data:
  airflow-data:
  postgres-data:
  vault-data:
  keycloak-data:
  prometheus-data:
  grafana-data:
  loki-data:
  superset-data:
  openmetadata-data:
  redis-data:
  spark-data:

services:
  base-init:
    image: hello-world
    networks:
      - frontend-net
      - backend-net
      - management-net
      - keycloak-net
