networks:
  backend-net:
    external: true
    name: docker_backend-net
  frontend-net:
    external: true
    name: docker_frontend-net

volumes:
  clickhouse-data:
    external: true
    name: docker_clickhouse-data
  spark-data:
    external: true
    name: docker_spark-data

services:

  clickhouse:
    image: clickhouse/clickhouse-server:23.8-alpine
    container_name: clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9002:9000"
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: Click@2024
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    networks:
      - backend-net
      - frontend-net
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    restart: unless-stopped
    ports:
      - "8081:8080"
      - "7077:7077"
    environment:
      SPARK_NO_DAEMONIZE: true
    volumes:
      - spark-data:/opt/spark/work
    networks:
      - backend-net
      - frontend-net
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master

  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    restart: unless-stopped
    environment:
      SPARK_NO_DAEMONIZE: true
    volumes:
      - spark-data:/opt/spark/work
    depends_on:
      - spark-master
    networks:
      - backend-net
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
