-- generated by nl_dbt_agent
-- model: fct_revenue_by_plan

{{ config(schema='gold', materialized='table', engine='MergeTree()', order_by='tuple()') }}

SELECT
    plan,
    toStartOfMonth(started_at) AS month,
    round(sum(mrr), 2) AS revenue
FROM {{ ref('stg_subscriptions') }}
WHERE started_at IS NOT NULL
GROUP BY plan, month
ORDER BY month, plan
