-- generated by nl_dbt_agent
-- model: fct_monthly_revenue_by_category

{{ config(schema='gold', materialized='table', engine='MergeTree()', order_by='tuple()') }}

SELECT
  toStartOfMonth(order_date) AS month,
  dp.category,
  round(sum(fo.revenue), 2) AS revenue
FROM {{ ref('fct_orders') }} fo
JOIN {{ ref('dim_products') }} dp ON fo.product_key = dp.product_key
GROUP BY month, category
ORDER BY month, category