-- generated by nl_dbt_agent
-- model: fct_loyal_customers

{{ config(schema='gold', materialized='table', engine='MergeTree()', order_by='tuple()') }}

WITH loyal_customers AS (
    SELECT
        dc.customer_key,
        dc.full_name,
        dc.country,
        SUM(fo.revenue) AS total_revenue,
        COUNT(fo.order_id) AS order_count
    FROM gold.fct_orders fo
    JOIN gold.dim_customers dc ON fo.customer_key = dc.customer_key AND dc.is_current = 1
    GROUP BY dc.customer_key, dc.full_name, dc.country
    HAVING COUNT(fo.order_id) > 5 AND SUM(fo.revenue) > 1000
)

SELECT * FROM loyal_customers