-- generated by nl_dbt_agent
-- model: fct_vendor_performance

{{ config(schema='gold', materialized='table', engine='MergeTree()', order_by='tuple()') }}

WITH vendor_performance AS ( SELECT vendor_key, COUNT(CASE WHEN delivery_date <= po_date + INTERVAL lead_time_days DAY THEN 1 END) AS on_time_deliveries, COUNT(*) AS total_orders, SUM(amount) AS total_amount, COUNT(po_id) AS order_count FROM {{ ref('fct_procurement') }} GROUP BY vendor_key ) SELECT vp.vendor_key, dv.name AS vendor_name, vp.total_orders, vp.on_time_deliveries, (vp.on_time_deliveries / vp.total_orders) * 100 AS on_time_delivery_rate, vp.total_amount / vp.order_count AS average_order_size FROM vendor_performance vp LEFT JOIN {{ ref('dim_vendors') }} dv ON vp.vendor_key = dv.vendor_key