-- generated by nl_dbt_agent
-- model: fct_rolling_revenue_by_category

{{ config(schema='gold', materialized='table', engine='MergeTree()', order_by='tuple()') }}

WITH daily_revenue AS (
  SELECT product_category, revenue, order_date_day
  FROM {{ ref('fct_orders') }}
  WHERE status = 'completed'
)
, rolling_revenue AS (
  SELECT product_category, SUM(revenue) AS total_revenue
  FROM daily_revenue
  WHERE order_date_day >= now() - INTERVAL 30 DAY
  GROUP BY product_category
)
SELECT * FROM rolling_revenue