-- generated by nl_dbt_agent
-- model: fct_monthly_revenue_by_category

{{ config(schema='gold', materialized='table', engine='MergeTree()', order_by='tuple()') }}

-- generated by nl_dbt_agent
-- model: fct_monthly_revenue_by_category

SELECT toStartOfMonth(o.order_date) AS month, p.category AS product_category, sum(o.revenue) AS revenue FROM {{ ref('fct_orders') }} o JOIN {{ ref('dim_products') }} p ON o.product_key = p.product_key WHERE p.is_current = 1 AND o.order_date >= subtractDays(today(), 180) GROUP BY month, product_category ORDER BY month, product_category