-- generated by nl_dbt_agent
-- model: fct_monthly_revenue_trend_by_category

{{ config(schema='gold', materialized='table', engine='MergeTree()', order_by='tuple()') }}

SELECT
  curr.month,
  curr.category,
  curr.revenue,
  prev.revenue AS prev_revenue,
  if(prev.revenue > 0,
     round((curr.revenue - prev.revenue) / prev.revenue * 100, 1),
     NULL) AS mom_growth_pct
FROM (
  SELECT toStartOfMonth(order_date) AS month,
         product_category AS category,
         round(sum(revenue), 2) AS revenue
  FROM {{ ref('fct_orders') }}
  WHERE order_date >= subtractDays(today(), 180)
  GROUP BY month, category
) curr
LEFT JOIN (
  SELECT toStartOfMonth(order_date) AS month,
         product_category AS category,
         round(sum(revenue), 2) AS revenue
  FROM {{ ref('fct_orders') }}
  GROUP BY month, category
) prev ON curr.month = addMonths(prev.month, 1) AND curr.category = prev.category
ORDER BY curr.month, curr.category