-- generated by nl_dbt_agent
-- model: fct_customer_churn_rate

{{ config(schema='gold', materialized='table', engine='MergeTree()', order_by='tuple()') }}

WITH monthly_churn AS ( SELECT toStartOfMonth(created_at) AS month, countIf(is_churned = 1) AS churned, count() AS total FROM {{ ref('dim_users') }} GROUP BY month ) SELECT month, round(churned / total * 100, 1) AS churn_rate FROM monthly_churn ORDER BY month