-- generated by nl_dbt_agent
-- model: fct_mrr_by_plan

{{ config(schema='gold', materialized='table', engine='MergeTree()', order_by='plan') }}

SELECT
    plan,
    sum(total_mrr) AS total_mrr
FROM {{ ref('fct_mrr') }}
GROUP BY plan
ORDER BY total_mrr DESC