{{
    config(
        materialized         = 'incremental',
        incremental_strategy = 'delete+insert',
        unique_key           = 'product_id',
        engine               = 'ReplacingMergeTree(enriched_at)',
        order_by             = 'product_id',
        schema               = 'gold',
    )
}}

-- generated by nl_dbt_agent
-- Reads AI-enriched product records from raw.shopflow_products_enriched
-- and exposes them in the gold layer for the Insight Agent and Superset.
SELECT
    product_id,
    product_name,
    original_category,
    enriched_category,
    sentiment,
    quality_tier,
    keywords,
    enriched_at
FROM {{ source('raw', 'shopflow_products_enriched') }}

{% if is_incremental() %}
WHERE enriched_at > (
    SELECT max(enriched_at) - toIntervalHour(1)
    FROM {{ this }}
)
{% endif %}
