"""
Streaming Enrichment DAG
========================
DAG ID  : streaming_enrichment
Schedule: every 5 minutes  (*/5 * * * *)
Owner   : shopflow-datalake
Tags    : streaming, enrichment, real-time

PURPOSE
-------
The ShopFlow domain captures product changes in MySQL via Debezium CDC.  Raw CDC
events contain only the relational fields that exist in the source system (name,
category, price) — they carry no analytical enrichment.  This DAG closes that gap
by reading product change events from Kafka in near-real-time and running each
batch through a Groq LLM call that adds four derived fields:

  sentiment          positive | neutral | negative
                     Derived from product name, category, and price signals.
                     Positive = high-quality / popular tier; negative = cheap
                     or generically named; neutral = everything else.

  quality_tier       premium | standard | budget
                     Rule-anchored: premium if price > 100 or luxury category;
                     budget if price < 20 or generic branding; standard otherwise.

  enriched_category  A more specific subcategory label (e.g. "Electronics" →
                     "Wireless Earbuds") generated by the LLM from product context.

  keywords           Array of 3–5 descriptive tags for search and filtering
                     (e.g. ["noise-cancelling", "Bluetooth", "portable"]).

WHY KAFKA + DEBEZIUM INSTEAD OF BATCH POLLING
---------------------------------------------
Polling the MySQL source on a fixed schedule (e.g. hourly) requires either a
reliable updated_at column or a full-table diff — both fragile at scale.
Debezium tails the MySQL binary log and emits every INSERT / UPDATE / DELETE
to Kafka topic dbz.shopflow.products in under a second.  This DAG therefore
only needs to consume from Kafka; it never touches MySQL directly.

A five-minute Airflow schedule is a pragmatic compromise: it gives products
enriched labels within minutes of creation, while avoiding the operational
overhead of a continuously-running Flink or Spark Streaming job.

DATA FLOW
---------
    MySQL binlog
        │
        ▼ (Debezium Kafka Connect)
    Kafka topic: dbz.shopflow.products
        │
        ▼ Task 1: consume_and_enrich  (up to 200 msgs / run, batches of 10)
    raw.shopflow_products_enriched   ← ReplacingMergeTree(enriched_at)
        │                               deduplicates by product_id on merge
        ▼ Task 2: run_dbt_mart        (only when new records written)
    gold.mart_product_enrichment     ← dbt model reads from raw table
        │
        ▼ Task 3: reload_rag          (only when dbt mart succeeded)
    AI Agent ChromaDB                ← gold schema re-indexed so Insight agent
                                        can answer enrichment questions

TASK DEPENDENCY GRAPH
---------------------
    consume_and_enrich ──► run_dbt_mart ──► reload_rag

XCom gates control conditional execution:
  • run_dbt_mart  only runs if records_enriched > 0   (xcom key: records_enriched)
  • reload_rag    only runs if mart_refreshed = True   (xcom key: mart_refreshed)
This prevents unnecessary dbt compiles and RAG index rebuilds on idle Kafka runs.

GROQ ENRICHMENT DETAILS
-----------------------
Model   : meta-llama/llama-4-scout-17b-16e-instruct
Batching: 10 products per API call (BATCH_SIZE).  Smaller batches reduce token
          usage and stay within Groq's per-request limits; a 0.5 s sleep between
          batches avoids TPM rate-limit 429 errors.
Prompt  : Returns a strict JSON array with exactly len(batch) objects.
          Markdown code fences are stripped if the model wraps the response.
Fallback: If the API call fails for any reason, neutral/standard/original_category
          defaults are inserted so the pipeline does not stall.  Products with
          defaults are indistinguishable from real enrichments in the schema,
          which is intentional — the pipeline prefers liveness over accuracy.

KAFKA CONSUMER SETTINGS
-----------------------
  POLL_TIMEOUT_MS = 15 000 ms
    Kafka's group coordinator handshake typically takes 5–10 s on the first
    connection.  Setting consumer_timeout_ms below this causes the consumer to
    exit before receiving any messages.  15 s is a safe margin for the Docker
    network round-trip inside Compose.

  auto_offset_reset = 'earliest'
    On first run (new consumer group) the consumer reads all accumulated product
    events, not just new ones.  This bootstraps the enriched table from the
    complete product history rather than only future changes.

  MAX_MESSAGES = 200 per DAG run
    Prevents a single run from consuming unbounded messages when the consumer
    group is far behind.  With a 5-minute schedule and a 4-minute execution
    timeout, 200 messages at ~2 Groq calls/s is comfortably within bounds.

  ReplacingMergeTree(enriched_at)
    The ClickHouse target table uses the product_id as its ORDER BY key.
    ReplacingMergeTree keeps the row with the latest enriched_at on background
    merge — so re-enriching an existing product (e.g. after a price update) is
    an idempotent upsert rather than an ever-growing append.

ENVIRONMENT VARIABLES
---------------------
  KAFKA_BOOTSTRAP_SERVERS   kafka:9092 (default)
  GROQ_API_KEY              required for live enrichment; empty → LLM calls fail
  GROQ_MODEL                meta-llama/llama-4-scout-17b-16e-instruct (default)
  CLICKHOUSE_URL            http://clickhouse:8123/ (default)
  DBT_CLICKHOUSE_USER       default
  DBT_CLICKHOUSE_PASSWORD   —
  AI_AGENT_URL              http://172.17.0.1:8502 (Docker bridge gateway to host)
  DATALAKE_HOME             /opt/datalake; used to resolve the dbt project path

FAILURE MODES
-------------
• Kafka not running / unreachable  → NoBrokersAvailable caught; task logs INFO
                                     and exits cleanly; records_enriched = 0;
                                     downstream tasks are skipped.

• Groq API error / rate limit      → Exception caught per batch; neutral defaults
                                     inserted for that batch; pipeline continues.

• ClickHouse INSERT fails          → Unhandled exception; task fails; Airflow
                                     retries 2× with 2-minute delay.

• dbt mart fails                   → Non-fatal: logged as WARN; mart_refreshed
                                     not pushed; reload_rag skipped.  Raw table
                                     still contains enriched data; mart refreshes
                                     on the next successful cycle.

• RAG reload fails                 → Non-fatal: logged as WARN; AI Agent continues
                                     serving queries against the previous schema
                                     snapshot until the next successful reload.
"""

import json
import os
from datetime import datetime, timedelta

from airflow import DAG
from airflow.operators.python import PythonOperator

KAFKA_BOOTSTRAP = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "kafka:9092")
KAFKA_TOPIC     = "dbz.shopflow.products"
KAFKA_GROUP_ID  = "airflow-enrichment-consumer"

GROQ_API_KEY    = os.getenv("GROQ_API_KEY", "")
GROQ_MODEL      = os.getenv("GROQ_MODEL", "meta-llama/llama-4-scout-17b-16e-instruct")

CH_URL      = os.getenv("CLICKHOUSE_URL", "http://clickhouse:8123/")
CH_USER     = os.getenv("DBT_CLICKHOUSE_USER", "default")
CH_PASSWORD = os.getenv("DBT_CLICKHOUSE_PASSWORD", "")

AI_AGENT_URL  = os.getenv("AI_AGENT_URL", "http://172.17.0.1:8502")
DATALAKE_HOME = os.getenv("DATALAKE_HOME", "/opt/datalake")
DBT_PROJECT   = f"{DATALAKE_HOME}/transformation/dbt/datalake_transforms"
DBT_PROFILES  = "/opt/airflow/dbt_profiles.yml"
DBT_BIN       = "/home/airflow/.local/bin/dbt"

BATCH_SIZE       = 10    # products per Groq call — avoids rate limits
POLL_TIMEOUT_MS  = 15000 # ms to wait for Kafka messages (group coordinator handshake needs ~5s+)
MAX_MESSAGES     = 200   # max messages per DAG run


def _ch(sql: str) -> str:
    import requests
    resp = requests.post(CH_URL, data=sql, auth=(CH_USER, CH_PASSWORD), timeout=30)
    resp.raise_for_status()
    return resp.text.strip()


def _ensure_raw_table():
    """Create raw.shopflow_products_enriched if it doesn't exist."""
    _ch("CREATE DATABASE IF NOT EXISTS raw")
    _ch("""
        CREATE TABLE IF NOT EXISTS raw.shopflow_products_enriched (
            product_id         UInt64,
            product_name       String,
            original_category  String,
            enriched_category  String,
            sentiment          LowCardinality(String),
            quality_tier       LowCardinality(String),
            keywords           Array(String),
            enriched_at        DateTime DEFAULT now()
        ) ENGINE = ReplacingMergeTree(enriched_at)
        ORDER BY product_id
    """)


def _enrich_batch_with_groq(products: list[dict]) -> list[dict]:
    """
    Call Groq to enrich a batch of products.
    Returns list of enrichment dicts: {product_id, sentiment, quality_tier,
                                        enriched_category, keywords}
    Falls back to neutral/standard/original_category on any error.
    """
    from groq import Groq

    client = Groq(api_key=GROQ_API_KEY)

    product_text = "\n".join(
        f"{i+1}. id={p.get('product_id', p.get('id','?'))} "
        f"name={p.get('name', p.get('product_name','?'))} "
        f"category={p.get('category','?')} price={p.get('price','?')}"
        for i, p in enumerate(products)
    )

    prompt = f"""You are a product classification assistant. Analyze these products and return ONLY a JSON array.

Products:
{product_text}

Return a JSON array with exactly {len(products)} objects, one per product, in order:
[
  {{
    "product_id": <number>,
    "sentiment": "positive" | "neutral" | "negative",
    "quality_tier": "premium" | "standard" | "budget",
    "enriched_category": "<specific subcategory>",
    "keywords": ["<tag1>", "<tag2>", "<tag3>"]
  }}
]

Rules:
- sentiment: positive=high-quality/popular/well-reviewed, negative=cheap/problematic/low-quality, neutral=average
- quality_tier: premium=price>100 or luxury category, budget=price<20 or generic, standard=everything else
- enriched_category: be more specific than the original (e.g. "Electronics" → "Smartphones")
- keywords: 3-5 descriptive tags
- Return ONLY the JSON array, no other text."""

    try:
        response = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
            max_tokens=1024,
        )
        raw = response.choices[0].message.content.strip()
        # Strip markdown code fences if present
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        return json.loads(raw.strip())
    except Exception as exc:
        print(f"  [WARN] Groq enrichment failed for batch: {exc}")
        # Return neutral defaults so pipeline doesn't stall
        return [
            {
                "product_id":        p.get("product_id", p.get("id", 0)),
                "sentiment":         "neutral",
                "quality_tier":      "standard",
                "enriched_category": p.get("category", "Unknown"),
                "keywords":          [],
            }
            for p in products
        ]


def consume_and_enrich(**ctx):
    """
    Poll Kafka for product CDC events, enrich via Groq, write to ClickHouse.
    Tracks whether this is the first successful enrichment run (for dbt trigger).
    """
    from kafka import KafkaConsumer
    from kafka.errors import NoBrokersAvailable

    _ensure_raw_table()

    # Try to connect to Kafka — non-fatal if not yet running
    try:
        consumer = KafkaConsumer(
            KAFKA_TOPIC,
            bootstrap_servers=KAFKA_BOOTSTRAP,
            group_id=KAFKA_GROUP_ID,
            auto_offset_reset="earliest",
            enable_auto_commit=True,
            value_deserializer=lambda m: json.loads(m.decode("utf-8", errors="replace")),
            consumer_timeout_ms=POLL_TIMEOUT_MS,
            session_timeout_ms=30000,
        )
    except NoBrokersAvailable:
        print("[INFO] Kafka not available yet — streaming pipeline not started. Skipping.")
        ctx["ti"].xcom_push(key="records_enriched", value=0)
        return
    except Exception as exc:
        print(f"[WARN] Kafka connection failed: {exc}. Skipping.")
        ctx["ti"].xcom_push(key="records_enriched", value=0)
        return

    # Collect messages up to MAX_MESSAGES
    raw_products = []
    try:
        for msg in consumer:
            value = msg.value
            if not value or not isinstance(value, dict):
                continue
            # Debezium JSON serializer wraps in {"schema":{...},"payload":{...}} even with
            # ExtractNewRecordState — unwrap to the actual row data
            if "payload" in value:
                value = value["payload"]
            raw_products.append(value)
            if len(raw_products) >= MAX_MESSAGES:
                break
    finally:
        consumer.close()

    if not raw_products:
        print("No new product messages in Kafka — nothing to enrich.")
        ctx["ti"].xcom_push(key="records_enriched", value=0)
        return

    print(f"Consumed {len(raw_products)} product messages. Enriching in batches of {BATCH_SIZE}...")

    all_enriched = []
    for i in range(0, len(raw_products), BATCH_SIZE):
        batch = raw_products[i : i + BATCH_SIZE]
        enriched = _enrich_batch_with_groq(batch)
        all_enriched.extend(enriched)
        # Small delay between Groq calls to respect rate limits
        import time
        if i + BATCH_SIZE < len(raw_products):
            time.sleep(0.5)

    if not all_enriched:
        ctx["ti"].xcom_push(key="records_enriched", value=0)
        return

    # Build name/category lookup from raw messages (Debezium uses product_id)
    id_to_raw = {p.get("product_id", p.get("id", 0)): p for p in raw_products}

    # Insert into ClickHouse raw table
    rows = []
    for item in all_enriched:
        pid  = int(item.get("product_id", 0))
        raw  = id_to_raw.get(pid, {})
        name = str(raw.get("name", "")).replace("'", "\\'")
        orig_cat = str(raw.get("category", item.get("enriched_category", "Unknown"))).replace("'", "\\'")
        enr_cat  = str(item.get("enriched_category", orig_cat)).replace("'", "\\'")
        sentiment = item.get("sentiment", "neutral")
        tier      = item.get("quality_tier", "standard")
        keywords  = item.get("keywords", [])
        kw_str    = "[" + ", ".join(f"'{k}'" for k in keywords[:5]) + "]"
        rows.append(
            f"({pid}, '{name}', '{orig_cat}', '{enr_cat}', "
            f"'{sentiment}', '{tier}', {kw_str}, now())"
        )

    _ch(
        "INSERT INTO raw.shopflow_products_enriched "
        "(product_id, product_name, original_category, enriched_category, "
        "sentiment, quality_tier, keywords, enriched_at) VALUES "
        + ", ".join(rows)
    )

    print(f"Inserted {len(rows)} enriched products into raw.shopflow_products_enriched")
    ctx["ti"].xcom_push(key="records_enriched", value=len(rows))


def run_dbt_mart(**ctx):
    """
    Run dbt mart_product_enrichment model to land enriched data in gold.
    Only runs when new records were enriched this cycle.
    """
    import subprocess

    records = ctx["ti"].xcom_pull(key="records_enriched", task_ids="consume_and_enrich") or 0
    if records == 0:
        print("No new records — skipping dbt mart refresh.")
        return

    dbt_exe = next(
        (d for d in [DBT_BIN, "/usr/local/bin/dbt", "/home/airflow/.local/bin/dbt"]
         if os.path.exists(d)),
        "dbt",
    )
    profiles_dir = (
        os.path.dirname(DBT_PROFILES)
        if os.path.exists(DBT_PROFILES)
        else os.path.expanduser("~/.dbt")
    )

    result = subprocess.run(
        [dbt_exe, "run",
         "--select", "mart_product_enrichment",
         "--project-dir", DBT_PROJECT,
         "--profiles-dir", profiles_dir,
         "--no-version-check",
         "--target-path", "/tmp/dbt_target"],
        capture_output=True, text=True, timeout=120,
    )

    if result.returncode != 0:
        # Non-fatal — raw table is still populated, mart will run next cycle
        print(f"[WARN] dbt mart_product_enrichment failed:\n{result.stderr[-500:]}")
    else:
        print("dbt mart_product_enrichment: OK")
        ctx["ti"].xcom_push(key="mart_refreshed", value=True)


def reload_rag(**ctx):
    """
    POST /api/rag/reload so the Insight Agent immediately knows about
    gold.mart_product_enrichment via the live schema sync.
    Only runs when the dbt mart was successfully refreshed.
    """
    import requests

    mart_refreshed = ctx["ti"].xcom_pull(key="mart_refreshed", task_ids="run_dbt_mart")
    if not mart_refreshed:
        return

    try:
        resp = requests.post(f"{AI_AGENT_URL}/api/rag/reload", timeout=20)
        resp.raise_for_status()
        print(f"RAG reloaded: {resp.json()}")
    except Exception as exc:
        print(f"[WARN] RAG reload failed (non-fatal): {exc}")


default_args = {
    "owner": "shopflow-datalake",
    "retries": 2,
    "retry_delay": timedelta(minutes=2),
    "email_on_failure": False,
}

with DAG(
    dag_id="streaming_enrichment",
    default_args=default_args,
    description="Every 5min: Kafka CDC → Groq enrichment → raw.shopflow_products_enriched → dbt gold mart",
    schedule_interval="*/5 * * * *",
    start_date=datetime(2026, 1, 1),
    catchup=False,
    max_active_runs=1,
    tags=["streaming", "enrichment", "real-time"],
) as dag:

    t1 = PythonOperator(
        task_id="consume_and_enrich",
        python_callable=consume_and_enrich,
        execution_timeout=timedelta(minutes=4),
    )

    t2 = PythonOperator(
        task_id="run_dbt_mart",
        python_callable=run_dbt_mart,
        execution_timeout=timedelta(minutes=3),
    )

    t3 = PythonOperator(
        task_id="reload_rag",
        python_callable=reload_rag,
        execution_timeout=timedelta(minutes=1),
    )

    t1 >> t2 >> t3
